# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QR Attendance' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QR Attendance

  target 'QR AttendanceTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'QR AttendanceUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'


end
